-- place this in one of your configuration file(s)
local hop = require('hop')
local directions = require('hop.hint').HintDirection
vim.keymap.set('n', '<leader>ja', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR })
end, {remap=true, desc="Search the prompted character in the following lines"})
vim.keymap.set('n', '<leader>jb', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR })
end, {remap=true, desc="Search the prompted character in the previous lines"})
vim.keymap.set('n', '<leader>jA', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, {remap=true, desc="Search the prompted character in this line, after the cursor"})
vim.keymap.set('n', '<leader>jB', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, {remap=true, desc="Search the prompted character in this line, before the cursor"})